### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by Shinji-ux** [Shinji-ux/furima-41418#20]
https://furima-41418.onrender.com/

**Comment by maru2628** [comment]
ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

**[修正依頼箇所]**
**商品購入機能の確認**
- [ ] **必要な情報を適切に入力して「購入」ボタンを押すと、商品の購入ができること**
必要な情報を入力し、購入ボタンを押すと、クレジットカード情報を入力していても
エラーが出て購入が完了しません。
ご確認と修正をお願いいたします。
※購入完了後の挙動のチェックは、次回ご提出時に併せて確認をさせていただきます。
ご認識のほどよろしくお願いいたします。
<img width="423" alt="スクリーンショット 2024-10-10 9 22 49" src="https://github.com/user-attachments/assets/8f1c748e-fa60-406a-baad-9a3e489f371d">

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。

https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by maru2628** [comment]
最終課題「FURIMA」の開発、お疲れ様です。

ご提出いただいたアプリケーションについて、正常に動作することを確認いたしました。
達成要件を満たしましたので、完了認定（LGTM）とさせていただきます。おめでとうございます。

_※ スタッフ側で実施した動作確認は必須機能についてのみです。追加機能についての動作確認は実施しておりません。追加機能を実装した場合は想定通りの挙動となっているか自分自身で確認をお願い致します。_
_※ Github上の最終課題の履歴はここまで頑張ってきたことの証となります。削除せず大切に保管するようにしましょう。_

![lgtm_01](https://user-images.githubusercontent.com/54050089/186354234-2de2a3d1-500d-4164-81d5-7585cdd03227.png)
